version: '3.2'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      back:
        ipv4_address: 10.5.0.5
  php:
    build: .docker
    volumes:
      - ~/.docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - '8000:80'
    networks:
      back:
    depends_on:
      - rabbitmq
volumes:
  rabbitmq_data:
  rabbitmq_log:

networks:
  back:
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/10
